export const GET_ALL_DECKS = 'GET_ALL_DECKS'
export const CREATE_DECK = 'CREATE_DECK'
export const CHANGE_DECK = 'CHANGE_DECK'
export const ADD_CARD = 'ADD_CARD'
export const CHANGE_CARD = 'CHANGE_CARD'
export const UPDATE_SCORE = 'UPDATE_SCORE'